openapi: 3.0.1
info:
  title: 練習用
  description: ''
  version: 0.1.0
tags:
  - name: player
paths:
  /players:
    get:
      summary: 選手取得API
      deprecated: false
      description: ''
      operationId: get-all-player
      tags:
        - player
      parameters: []
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  players:
                    type: array
                    items:
                      $ref: '#/components/schemas/Player'
                required:
                  - players
              examples:
                '1':
                  summary: 成功例
                  value:
                    players:
                      - id: 1
                        position: GK
                        name:
                          name: 円堂守
                          furigana: えんどうまもる
      security: []
components:
  schemas:
    Name:
      type: object
      properties:
        name:
          type: string
          example: 円堂守
        furigana:
          type: string
          example: えんどうまもる
      required:
        - name
        - furigana
    Player:
      type: object
      properties:
        id:
          type: integer
          description: ID番号
          example: '1'
        position:
          type: string
          description: ポジション
          example: GK
        name:
          $ref: '#/components/schemas/Name'
      required:
        - id
        - position
  securitySchemes: {}
servers: []